const cabins = [
    {
        id: 1,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "double",
        category: "A",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 2,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "double",
        category: "A",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 3,
        guestOne: "Spiderman",
        guestTwo: "Mitsos",
        bed: "flex",
        category: "A",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 4,
        guestOne: "John Doe",
        guestTwo: "Koula",
        bed: "double",
        category: "B",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 5,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "twin",
        category: "B",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 6,
        guestOne: "Ignjat",
        guestTwo: "Zombi",
        bed: "double",
        category: "C",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 7,
        guestOne: "Jesus",
        guestTwo: "Lebowski",
        bed: "twin",
        category: "C",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 8,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "triple",
        category: "P",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 9,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "double",
        category: "P",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 10,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "double",
        category: "P",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
    {
        id: 11,
        guestOne: "John Doe",
        guestTwo: "Milenko",
        bed: "double",
        category: "P",
        remarks: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, animi.",
    },
]